apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    http_port = 3000

    [auth]
    disable_login_form = false
    disable_signout_menu = false

    [security]
    admin_password = "admin123"  # Change this to a secure password
