apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 31309 # Optional: Specify the node port or let Kubernetes assign one
  selector:
    app: prometheus-server # Match this with your deployment label
